"""
Abstract base class for all trading strategies.

Every strategy must implement this interface to be compatible
with the backtesting engine, optimizer, and reporting pipeline.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

import pandas as pd


class Signal(Enum):
    """Trading signal generated by a strategy on each bar."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class StrategySignal:
    """
    A signal emitted by a strategy for a specific bar.

    Attributes:
        action: BUY, SELL, or HOLD.
        price: Suggested entry/exit price (usually the Close).
        stop_loss: Suggested stop-loss price (optional).
        take_profit: Suggested take-profit price (optional).
        position_size: Number of shares/units to trade (optional; engine may override).
        reason: Human-readable reason for the signal.
    """
    action: Signal
    price: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size: Optional[int] = None
    reason: str = ""


class Strategy(ABC):
    """
    Abstract base class for a bar-by-bar trading strategy.

    Lifecycle:
        1. __init__() — set parameters
        2. init(data)  — pre-calculate indicators on the full dataset
        3. next(i, data) — called for each bar index i (no look-ahead!)
        4. get_param_grid() — return parameter ranges for optimization
    """

    name: str = "BaseStrategy"
    version: int = 0

    def __init__(self, params: Optional[Dict[str, Any]] = None):
        """
        Initialize strategy with parameters.

        Args:
            params: Dict of strategy-specific parameters.
                    Keys should match the strategy's expected parameters.
        """
        self.params: Dict[str, Any] = params or {}

    @abstractmethod
    def init(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        Pre-calculate technical indicators on the full dataset.

        This is called ONCE before the bar-by-bar loop.
        The strategy may add indicator columns to the dataframe.

        IMPORTANT: Although this sees the full dataset, the next() method
        must only use data up to index i to avoid look-ahead bias.

        Args:
            data: OHLCV DataFrame with columns [Date, Open, High, Low, Close, Volume].

        Returns:
            DataFrame with added indicator columns.
        """
        ...

    @abstractmethod
    def next(self, i: int, data: pd.DataFrame) -> StrategySignal:
        """
        Generate a signal for bar at index i.

        CRITICAL: Must only access data.iloc[:i+1] (current and past bars).
        Accessing future bars (i+1, i+2, ...) introduces look-ahead bias.

        Args:
            i: Current bar index (0-based).
            data: Full DataFrame with pre-calculated indicators.

        Returns:
            StrategySignal with action, price, and optional SL/TP.
        """
        ...

    def get_param_grid(self) -> Dict[str, List[Any]]:
        """
        Return parameter grid for optimization.

        Override in subclasses to define optimizable parameter ranges.

        Returns:
            Dict mapping parameter name -> list of values to test.
            Example: {"short_window": [10, 15, 20], "long_window": [30, 40, 50]}
        """
        return {}

    def get_default_params(self) -> Dict[str, Any]:
        """
        Return default parameter values.

        Override in subclasses.
        """
        return {}

    def set_params(self, params: Dict[str, Any]) -> None:
        """Update strategy parameters."""
        self.params.update(params)

    def __repr__(self) -> str:
        return f"{self.name}(v{self.version}, params={self.params})"
